/*
 * Employment Action Types
 */

/* Employment Cards */
export const GET_EMPLOYMENTS_SUCCESS = "GET_EMPLOYMENTS_SUCCESS";
export const GET_EMPLOYMENTS_FAILED = "GET_EMPLOYMENTS_FAILED";

export const GET_CASEBUTTONS_SUCCESS = "GET_CASEBUTTONS_SUCCESS";
export const GET_CASEBUTTONS_FAILED = "GET_CASEBUTTONS_FAILED";

export const GET_SALARY_SUCCESS = "GET_SALARY_SUCCESS";
export const GET_SALARY_FAILED = "GET_SALARY_FAILED";

export const GET_SALARY_AFFECTING_SUCCESS = "GET_SALARY_AFFECTING_SUCCESS";
export const GET_SALARY_AFFECTING_FAILED = "GET_SALARY_AFFECTING_FAILED";